version: 0.0.{build}

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

build_script: build.cmd pack

test: off
#  assemblies:
#    - __compile\RethinkDb.Driver.Tests.dll

after_build:
    - 7z a __package\RethinkDb.Driver.zip %APPVEYOR_BUILD_FOLDER%\__compile\RethinkDb.Driver.*
    - 7z a __package\RethinkDb.Driver.zip %APPVEYOR_BUILD_FOLDER%\__compile\Newtonsoft.Json.*

artifacts:
    - path: __package\*.nupkg
      name: NuGet
    - path: __package\RethinkDb.Driver.zip
      name: Zip

nuget:
    disable_publish_on_pr: true

deploy:
    - provider: GitHub
      release: 'Release $(APPVEYOR_BUILD_VERSION)'
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
      prerelease: $(IsPreRelease)
      artifact: Zip, NuGet
      auth_token:
          secure: cyivrWQwrZNAb6UCNXlIQlGfVSnKIC6TatUOIP95CQgMeKGnmBSqBgAFv2TsRZhR
      on:
          branch: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true

    - provider: NuGet
      api_key:
          secure: 1nPS2ttf+N4+FUhd+GZycrL7YzSWQpZjnGOMCb5+pGJXSdx0IFvVF8xhTGna7B9t
      artifact: NuGet
      on:
          branch: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true
