version: '{build}'

environment:
  test_token:
    secure: yZJYlhNNEFmeZtRQg41ZyhlEBBUeO9+1NGXKWf43dR958gMNskGCucokVRGJkmJC

skip_commits:
  message: /read\W{0,1}me*/

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

build_script: build.cmd ci

after_build:
    - robocopy Source\RethinkDb.Driver\bin\Release __compile\RethinkDb.Driver\Release\other\ Common.Logging* Newtonsoft.Json* & if %errorlevel% LSS 8 exit /b 0 else exit /b 1
    - 7z a __package\RethinkDb.Driver.zip %APPVEYOR_BUILD_FOLDER%\__compile\RethinkDb.Driver\Release\**

before_test:

test: off


artifacts:
    - path: __package\*.nupkg
      name: NuGet
    - path: __package\RethinkDb.Driver.zip
      name: Zip

nuget:
    disable_publish_on_pr: true

deploy:
    - provider: GitHub
      release: 'Release $(APPVEYOR_REPO_TAG_NAME) build $(APPVEYOR_BUILD_VERSION)'
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
      prerelease: $(IsPreRelease)
      artifact: Zip, NuGet
      auth_token:
          secure: cyivrWQwrZNAb6UCNXlIQlGfVSnKIC6TatUOIP95CQgMeKGnmBSqBgAFv2TsRZhR
      on:
          branch: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true

    - provider: NuGet
      api_key:
          secure: 1nPS2ttf+N4+FUhd+GZycrL7YzSWQpZjnGOMCb5+pGJXSdx0IFvVF8xhTGna7B9t
      artifact: NuGet
      on:
          branch: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true

on_failure:
    - ps: |
            # Enables RDP for debugging and setup some tools
            $blockRdp = $true; choco install notepad2; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
            
